services:
  phosphobot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phosphobot-service
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    ports:
      - "3000:80"
  yolo-api:
    build:
      context: ../yolo-api
      dockerfile: Dockerfile
    container_name: yolo-service
    ports:
      - "8085:8000"
